### ISSUE TITLE
Soft Fluid handling adds empty Compound NBT tag to Forge fluids that had null NBT.

### ISSUE THREAD

**Issue by Random832** [MehVahdJukaar/Selene#1]
When you e.g. use a Supplementaries faucet to put a fluid that does not have NBT in a Forge fluid handler, it will put an empty NBT tag rather than null, which will cause it not to be considered equal to the original fluid by most mods.

I believe this issue is caused by the use of getOrCreateTag in https://github.com/MehVahdJukaar/Selene/blob/HEAD/src/main/java/net/mehvahdjukaar/selene/fluids/SoftFluidHolder.java#L559 .

**Comment by MehVahdJukaar** [comment]
I hadn't thought of that, I thought null or empty tags were treated the same as far as forge fluids went. I'll fix it
