### ISSUE TITLE
Vivecraft compatibility

### ISSUE THREAD

**Issue by Techjar** [MehVahdJukaar/Selene#11]
Hi, I'm one of the Vivecraft devs. Your mod currently crashes when loaded with Vivecraft, due to this mixin failing as it conflicts with one of our patches: https://github.com/MehVahdJukaar/Selene/blob/master/src/main/java/net/mehvahdjukaar/selene/mixins/FirstPersonRendererMixin.java Since it appears to just be a handler for first person animations, which I don't think would look right in VR anyways, it'd probably be fine to just disable it when Vivecraft is detected or otherwise have the mixin not crash the game when it fails.

**Comment by MehVahdJukaar** [comment]
Ok I made that moxin non required so it shouldn't crash when failing to apply
